//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientVehicle.ServerReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rent", Namespace="http://schemas.datacontract.org/2004/07/WCF_Rent.HeaderFile")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientVehicle.ServerReference.Vehicle))]
    public partial class Rent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FinalDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RentLogIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FinalDate {
            get {
                return this.FinalDateField;
            }
            set {
                if ((this.FinalDateField.Equals(value) != true)) {
                    this.FinalDateField = value;
                    this.RaisePropertyChanged("FinalDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RentLogId {
            get {
                return this.RentLogIdField;
            }
            set {
                if ((this.RentLogIdField.Equals(value) != true)) {
                    this.RentLogIdField = value;
                    this.RaisePropertyChanged("RentLogId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vehicle", Namespace="http://schemas.datacontract.org/2004/07/WCF_Rent.HeaderFile")]
    [System.SerializableAttribute()]
    public partial class Vehicle : ClientVehicle.ServerReference.Rent {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float FuelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float MaxFuelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxSpeedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float MileageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PicturePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransmissionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VINField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Fuel {
            get {
                return this.FuelField;
            }
            set {
                if ((this.FuelField.Equals(value) != true)) {
                    this.FuelField = value;
                    this.RaisePropertyChanged("Fuel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float MaxFuel {
            get {
                return this.MaxFuelField;
            }
            set {
                if ((this.MaxFuelField.Equals(value) != true)) {
                    this.MaxFuelField = value;
                    this.RaisePropertyChanged("MaxFuel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxSpeed {
            get {
                return this.MaxSpeedField;
            }
            set {
                if ((this.MaxSpeedField.Equals(value) != true)) {
                    this.MaxSpeedField = value;
                    this.RaisePropertyChanged("MaxSpeed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Mileage {
            get {
                return this.MileageField;
            }
            set {
                if ((this.MileageField.Equals(value) != true)) {
                    this.MileageField = value;
                    this.RaisePropertyChanged("Mileage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PicturePath {
            get {
                return this.PicturePathField;
            }
            set {
                if ((object.ReferenceEquals(this.PicturePathField, value) != true)) {
                    this.PicturePathField = value;
                    this.RaisePropertyChanged("PicturePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Plate {
            get {
                return this.PlateField;
            }
            set {
                if ((object.ReferenceEquals(this.PlateField, value) != true)) {
                    this.PlateField = value;
                    this.RaisePropertyChanged("Plate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Transmission {
            get {
                return this.TransmissionField;
            }
            set {
                if ((object.ReferenceEquals(this.TransmissionField, value) != true)) {
                    this.TransmissionField = value;
                    this.RaisePropertyChanged("Transmission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VIN {
            get {
                return this.VINField;
            }
            set {
                if ((object.ReferenceEquals(this.VINField, value) != true)) {
                    this.VINField = value;
                    this.RaisePropertyChanged("VIN");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatInfo", Namespace="http://schemas.datacontract.org/2004/07/WCF_Rent.Structures")]
    [System.SerializableAttribute()]
    public partial class StatInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime endDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime startDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientVehicle.ServerReference.StatBalanceInfo[] statBalancesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientVehicle.ServerReference.StatVehicleInfo[] statVehiclesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientVehicle.ServerReference.StatVoucherInfo[] statVouchersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float totalbalanceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                if ((this.endDateField.Equals(value) != true)) {
                    this.endDateField = value;
                    this.RaisePropertyChanged("endDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                if ((this.startDateField.Equals(value) != true)) {
                    this.startDateField = value;
                    this.RaisePropertyChanged("startDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientVehicle.ServerReference.StatBalanceInfo[] statBalances {
            get {
                return this.statBalancesField;
            }
            set {
                if ((object.ReferenceEquals(this.statBalancesField, value) != true)) {
                    this.statBalancesField = value;
                    this.RaisePropertyChanged("statBalances");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientVehicle.ServerReference.StatVehicleInfo[] statVehicles {
            get {
                return this.statVehiclesField;
            }
            set {
                if ((object.ReferenceEquals(this.statVehiclesField, value) != true)) {
                    this.statVehiclesField = value;
                    this.RaisePropertyChanged("statVehicles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientVehicle.ServerReference.StatVoucherInfo[] statVouchers {
            get {
                return this.statVouchersField;
            }
            set {
                if ((object.ReferenceEquals(this.statVouchersField, value) != true)) {
                    this.statVouchersField = value;
                    this.RaisePropertyChanged("statVouchers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float totalbalance {
            get {
                return this.totalbalanceField;
            }
            set {
                if ((this.totalbalanceField.Equals(value) != true)) {
                    this.totalbalanceField = value;
                    this.RaisePropertyChanged("totalbalance");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatBalanceInfo", Namespace="http://schemas.datacontract.org/2004/07/WCF_Rent.Structures")]
    [System.SerializableAttribute()]
    public partial class StatBalanceInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientVehicle.ServerReference.Account accountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float cardnumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientVehicle.ServerReference.Account account {
            get {
                return this.accountField;
            }
            set {
                if ((object.ReferenceEquals(this.accountField, value) != true)) {
                    this.accountField = value;
                    this.RaisePropertyChanged("account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float cardnumber {
            get {
                return this.cardnumberField;
            }
            set {
                if ((this.cardnumberField.Equals(value) != true)) {
                    this.cardnumberField = value;
                    this.RaisePropertyChanged("cardnumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateTime {
            get {
                return this.dateTimeField;
            }
            set {
                if ((this.dateTimeField.Equals(value) != true)) {
                    this.dateTimeField = value;
                    this.RaisePropertyChanged("dateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float value {
            get {
                return this.valueField;
            }
            set {
                if ((this.valueField.Equals(value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatVehicleInfo", Namespace="http://schemas.datacontract.org/2004/07/WCF_Rent.Structures")]
    [System.SerializableAttribute()]
    public partial class StatVehicleInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientVehicle.ServerReference.Account accountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float creditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float paymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime rent_endDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime rent_startDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float returningField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int useridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientVehicle.ServerReference.Vehicle vehicleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VIN {
            get {
                return this.VINField;
            }
            set {
                if ((object.ReferenceEquals(this.VINField, value) != true)) {
                    this.VINField = value;
                    this.RaisePropertyChanged("VIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientVehicle.ServerReference.Account account {
            get {
                return this.accountField;
            }
            set {
                if ((object.ReferenceEquals(this.accountField, value) != true)) {
                    this.accountField = value;
                    this.RaisePropertyChanged("account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float credit {
            get {
                return this.creditField;
            }
            set {
                if ((this.creditField.Equals(value) != true)) {
                    this.creditField = value;
                    this.RaisePropertyChanged("credit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float payment {
            get {
                return this.paymentField;
            }
            set {
                if ((this.paymentField.Equals(value) != true)) {
                    this.paymentField = value;
                    this.RaisePropertyChanged("payment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime rent_endDate {
            get {
                return this.rent_endDateField;
            }
            set {
                if ((this.rent_endDateField.Equals(value) != true)) {
                    this.rent_endDateField = value;
                    this.RaisePropertyChanged("rent_endDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime rent_startDate {
            get {
                return this.rent_startDateField;
            }
            set {
                if ((this.rent_startDateField.Equals(value) != true)) {
                    this.rent_startDateField = value;
                    this.RaisePropertyChanged("rent_startDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float returning {
            get {
                return this.returningField;
            }
            set {
                if ((this.returningField.Equals(value) != true)) {
                    this.returningField = value;
                    this.RaisePropertyChanged("returning");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userid {
            get {
                return this.useridField;
            }
            set {
                if ((this.useridField.Equals(value) != true)) {
                    this.useridField = value;
                    this.RaisePropertyChanged("userid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientVehicle.ServerReference.Vehicle vehicle {
            get {
                return this.vehicleField;
            }
            set {
                if ((object.ReferenceEquals(this.vehicleField, value) != true)) {
                    this.vehicleField = value;
                    this.RaisePropertyChanged("vehicle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatVoucherInfo", Namespace="http://schemas.datacontract.org/2004/07/WCF_Rent.Structures")]
    [System.SerializableAttribute()]
    public partial class StatVoucherInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string operationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string timeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                if ((object.ReferenceEquals(this.operationField, value) != true)) {
                    this.operationField = value;
                    this.RaisePropertyChanged("operation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string time {
            get {
                return this.timeField;
            }
            set {
                if ((object.ReferenceEquals(this.timeField, value) != true)) {
                    this.timeField = value;
                    this.RaisePropertyChanged("time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/WCF_Rent.HeaderFile")]
    [System.SerializableAttribute()]
    public partial class Account : ClientVehicle.ServerReference.Admin {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int acceptedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float balanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateCreateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int documentidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fathernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string secondnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float totalMoneyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int accepted {
            get {
                return this.acceptedField;
            }
            set {
                if ((this.acceptedField.Equals(value) != true)) {
                    this.acceptedField = value;
                    this.RaisePropertyChanged("accepted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float balance {
            get {
                return this.balanceField;
            }
            set {
                if ((this.balanceField.Equals(value) != true)) {
                    this.balanceField = value;
                    this.RaisePropertyChanged("balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateCreate {
            get {
                return this.dateCreateField;
            }
            set {
                if ((this.dateCreateField.Equals(value) != true)) {
                    this.dateCreateField = value;
                    this.RaisePropertyChanged("dateCreate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int documentid {
            get {
                return this.documentidField;
            }
            set {
                if ((this.documentidField.Equals(value) != true)) {
                    this.documentidField = value;
                    this.RaisePropertyChanged("documentid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fathername {
            get {
                return this.fathernameField;
            }
            set {
                if ((object.ReferenceEquals(this.fathernameField, value) != true)) {
                    this.fathernameField = value;
                    this.RaisePropertyChanged("fathername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string secondname {
            get {
                return this.secondnameField;
            }
            set {
                if ((object.ReferenceEquals(this.secondnameField, value) != true)) {
                    this.secondnameField = value;
                    this.RaisePropertyChanged("secondname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float totalMoney {
            get {
                return this.totalMoneyField;
            }
            set {
                if ((this.totalMoneyField.Equals(value) != true)) {
                    this.totalMoneyField = value;
                    this.RaisePropertyChanged("totalMoney");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankCard", Namespace="http://schemas.datacontract.org/2004/07/WCF_Rent.HeaderFile")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientVehicle.ServerReference.Admin))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientVehicle.ServerReference.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientVehicle.ServerReference.Account))]
    public partial class BankCard : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CVVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpireDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CVV {
            get {
                return this.CVVField;
            }
            set {
                if ((this.CVVField.Equals(value) != true)) {
                    this.CVVField = value;
                    this.RaisePropertyChanged("CVV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberField, value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpireDate {
            get {
                return this.ExpireDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpireDateField, value) != true)) {
                    this.ExpireDateField = value;
                    this.RaisePropertyChanged("ExpireDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerName {
            get {
                return this.OwnerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerNameField, value) != true)) {
                    this.OwnerNameField = value;
                    this.RaisePropertyChanged("OwnerName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Admin", Namespace="http://schemas.datacontract.org/2004/07/WCF_Rent.HeaderFile")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientVehicle.ServerReference.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientVehicle.ServerReference.Account))]
    public partial class Admin : ClientVehicle.ServerReference.BankCard {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LevelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Level {
            get {
                return this.LevelField;
            }
            set {
                if ((this.LevelField.Equals(value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/WCF_Rent.HeaderFile")]
    [System.SerializableAttribute()]
    public partial class User : ClientVehicle.ServerReference.Admin {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BackImageNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthdayDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FrontImageNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] LicenseCategoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UserCreateDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BackImageName {
            get {
                return this.BackImageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BackImageNameField, value) != true)) {
                    this.BackImageNameField = value;
                    this.RaisePropertyChanged("BackImageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthdayDate {
            get {
                return this.BirthdayDateField;
            }
            set {
                if ((this.BirthdayDateField.Equals(value) != true)) {
                    this.BirthdayDateField = value;
                    this.RaisePropertyChanged("BirthdayDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FrontImageName {
            get {
                return this.FrontImageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FrontImageNameField, value) != true)) {
                    this.FrontImageNameField = value;
                    this.RaisePropertyChanged("FrontImageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] LicenseCategories {
            get {
                return this.LicenseCategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenseCategoriesField, value) != true)) {
                    this.LicenseCategoriesField = value;
                    this.RaisePropertyChanged("LicenseCategories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusReason {
            get {
                return this.StatusReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusReasonField, value) != true)) {
                    this.StatusReasonField = value;
                    this.RaisePropertyChanged("StatusReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UserCreateDate {
            get {
                return this.UserCreateDateField;
            }
            set {
                if ((this.UserCreateDateField.Equals(value) != true)) {
                    this.UserCreateDateField = value;
                    this.RaisePropertyChanged("UserCreateDate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CashVoucherData", Namespace="http://schemas.datacontract.org/2004/07/WCF_Rent.HeaderFile")]
    [System.SerializableAttribute()]
    public partial class CashVoucherData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string companyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string streetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string companyName {
            get {
                return this.companyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.companyNameField, value) != true)) {
                    this.companyNameField = value;
                    this.RaisePropertyChanged("companyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string path {
            get {
                return this.pathField;
            }
            set {
                if ((object.ReferenceEquals(this.pathField, value) != true)) {
                    this.pathField = value;
                    this.RaisePropertyChanged("path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string streetName {
            get {
                return this.streetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.streetNameField, value) != true)) {
                    this.streetNameField = value;
                    this.RaisePropertyChanged("streetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CashVoucher", Namespace="http://schemas.datacontract.org/2004/07/WCF_Rent.HeaderFile")]
    [System.SerializableAttribute()]
    public partial class CashVoucher : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FinalDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehicleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FinalDate {
            get {
                return this.FinalDateField;
            }
            set {
                if ((this.FinalDateField.Equals(value) != true)) {
                    this.FinalDateField = value;
                    this.RaisePropertyChanged("FinalDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vehicle {
            get {
                return this.VehicleField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleField, value) != true)) {
                    this.VehicleField = value;
                    this.RaisePropertyChanged("Vehicle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServerReference.IServiceRent", CallbackContract=typeof(ClientVehicle.ServerReference.IServiceRentCallback))]
    public interface IServiceRent {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/userConnect", ReplyAction="http://tempuri.org/IServiceRent/userConnectResponse")]
        int userConnect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/userConnect", ReplyAction="http://tempuri.org/IServiceRent/userConnectResponse")]
        System.Threading.Tasks.Task<int> userConnectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/userDisconnect", ReplyAction="http://tempuri.org/IServiceRent/userDisconnectResponse")]
        void userDisconnect(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/userDisconnect", ReplyAction="http://tempuri.org/IServiceRent/userDisconnectResponse")]
        System.Threading.Tasks.Task userDisconnectAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/selectAllVehicle")]
        void selectAllVehicle();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/selectAllVehicle")]
        System.Threading.Tasks.Task selectAllVehicleAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/deleteVehicle")]
        void deleteVehicle(ClientVehicle.ServerReference.Vehicle vehicleObject);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/deleteVehicle")]
        System.Threading.Tasks.Task deleteVehicleAsync(ClientVehicle.ServerReference.Vehicle vehicleObject);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/addVehicle")]
        void addVehicle(ClientVehicle.ServerReference.Vehicle vehicleObject);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/addVehicle")]
        System.Threading.Tasks.Task addVehicleAsync(ClientVehicle.ServerReference.Vehicle vehicleObject);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/saveVehicle")]
        void saveVehicle(ClientVehicle.ServerReference.Vehicle vehicleObject);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/saveVehicle")]
        System.Threading.Tasks.Task saveVehicleAsync(ClientVehicle.ServerReference.Vehicle vehicleObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/GetAllVehicle", ReplyAction="http://tempuri.org/IServiceRent/GetAllVehicleResponse")]
        int GetAllVehicle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/GetAllVehicle", ReplyAction="http://tempuri.org/IServiceRent/GetAllVehicleResponse")]
        System.Threading.Tasks.Task<int> GetAllVehicleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/GetAllRentVehicle", ReplyAction="http://tempuri.org/IServiceRent/GetAllRentVehicleResponse")]
        int GetAllRentVehicle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/GetAllRentVehicle", ReplyAction="http://tempuri.org/IServiceRent/GetAllRentVehicleResponse")]
        System.Threading.Tasks.Task<int> GetAllRentVehicleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/GetAllNoRentVehicle", ReplyAction="http://tempuri.org/IServiceRent/GetAllNoRentVehicleResponse")]
        int GetAllNoRentVehicle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/GetAllNoRentVehicle", ReplyAction="http://tempuri.org/IServiceRent/GetAllNoRentVehicleResponse")]
        System.Threading.Tasks.Task<int> GetAllNoRentVehicleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/findVehicle", ReplyAction="http://tempuri.org/IServiceRent/findVehicleResponse")]
        ClientVehicle.ServerReference.Vehicle findVehicle(string plate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/findVehicle", ReplyAction="http://tempuri.org/IServiceRent/findVehicleResponse")]
        System.Threading.Tasks.Task<ClientVehicle.ServerReference.Vehicle> findVehicleAsync(string plate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/uploadVehicleImage", ReplyAction="http://tempuri.org/IServiceRent/uploadVehicleImageResponse")]
        void uploadVehicleImage(byte[] buffer, string name, string extenstion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/uploadVehicleImage", ReplyAction="http://tempuri.org/IServiceRent/uploadVehicleImageResponse")]
        System.Threading.Tasks.Task uploadVehicleImageAsync(byte[] buffer, string name, string extenstion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/vehicleImage", ReplyAction="http://tempuri.org/IServiceRent/vehicleImageResponse")]
        byte[] vehicleImage(ClientVehicle.ServerReference.Vehicle item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/vehicleImage", ReplyAction="http://tempuri.org/IServiceRent/vehicleImageResponse")]
        System.Threading.Tasks.Task<byte[]> vehicleImageAsync(ClientVehicle.ServerReference.Vehicle item);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/log_AddVehicle")]
        void log_AddVehicle(int userid, string VIN);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/log_AddVehicle")]
        System.Threading.Tasks.Task log_AddVehicleAsync(int userid, string VIN);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/log_Balance")]
        void log_Balance(int userid, string card, float value);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/log_Balance")]
        System.Threading.Tasks.Task log_BalanceAsync(int userid, string card, float value);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/log_DeleteVehicle")]
        void log_DeleteVehicle(int userid, string VIN, string name);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/log_DeleteVehicle")]
        System.Threading.Tasks.Task log_DeleteVehicleAsync(int userid, string VIN, string name);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/log_EditVehicle")]
        void log_EditVehicle(int userid, string VIN, string str_params);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/log_EditVehicle")]
        System.Threading.Tasks.Task log_EditVehicleAsync(int userid, string VIN, string str_params);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/log_RemoveRent")]
        void log_RemoveRent(int userid, int takerentid, System.DateTime date, float balancereturn, float credit);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/log_RemoveRent")]
        System.Threading.Tasks.Task log_RemoveRentAsync(int userid, int takerentid, System.DateTime date, float balancereturn, float credit);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/log_Request")]
        void log_Request(int admin_userid, int application_userid, int answer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/log_Request")]
        System.Threading.Tasks.Task log_RequestAsync(int admin_userid, int application_userid, int answer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/log_TakeRent", ReplyAction="http://tempuri.org/IServiceRent/log_TakeRentResponse")]
        int log_TakeRent(int userid, string VIN, float price, int cashVoucherId, System.DateTime startdate, System.DateTime enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/log_TakeRent", ReplyAction="http://tempuri.org/IServiceRent/log_TakeRentResponse")]
        System.Threading.Tasks.Task<int> log_TakeRentAsync(int userid, string VIN, float price, int cashVoucherId, System.DateTime startdate, System.DateTime enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/SendStatInfo", ReplyAction="http://tempuri.org/IServiceRent/SendStatInfoResponse")]
        ClientVehicle.ServerReference.StatInfo SendStatInfo(System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/SendStatInfo", ReplyAction="http://tempuri.org/IServiceRent/SendStatInfoResponse")]
        System.Threading.Tasks.Task<ClientVehicle.ServerReference.StatInfo> SendStatInfoAsync(System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/selectVehicle", ReplyAction="http://tempuri.org/IServiceRent/selectVehicleResponse")]
        ClientVehicle.ServerReference.Vehicle selectVehicle(string VIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/selectVehicle", ReplyAction="http://tempuri.org/IServiceRent/selectVehicleResponse")]
        System.Threading.Tasks.Task<ClientVehicle.ServerReference.Vehicle> selectVehicleAsync(string VIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/sendCashVoucherData", ReplyAction="http://tempuri.org/IServiceRent/sendCashVoucherDataResponse")]
        ClientVehicle.ServerReference.CashVoucherData sendCashVoucherData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/sendCashVoucherData", ReplyAction="http://tempuri.org/IServiceRent/sendCashVoucherDataResponse")]
        System.Threading.Tasks.Task<ClientVehicle.ServerReference.CashVoucherData> sendCashVoucherDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/readCashVoucher", ReplyAction="http://tempuri.org/IServiceRent/readCashVoucherResponse")]
        ClientVehicle.ServerReference.CashVoucher readCashVoucher(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/readCashVoucher", ReplyAction="http://tempuri.org/IServiceRent/readCashVoucherResponse")]
        System.Threading.Tasks.Task<ClientVehicle.ServerReference.CashVoucher> readCashVoucherAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/writeCashVoucher", ReplyAction="http://tempuri.org/IServiceRent/writeCashVoucherResponse")]
        int writeCashVoucher(ClientVehicle.ServerReference.CashVoucher cashVoucher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/writeCashVoucher", ReplyAction="http://tempuri.org/IServiceRent/writeCashVoucherResponse")]
        System.Threading.Tasks.Task<int> writeCashVoucherAsync(ClientVehicle.ServerReference.CashVoucher cashVoucher);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/setCashVoucherData")]
        void setCashVoucherData(string Company, string Street);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/setCashVoucherData")]
        System.Threading.Tasks.Task setCashVoucherDataAsync(string Company, string Street);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/sendCashVoucherID", ReplyAction="http://tempuri.org/IServiceRent/sendCashVoucherIDResponse")]
        int sendCashVoucherID(int logtakerentid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/sendCashVoucherID", ReplyAction="http://tempuri.org/IServiceRent/sendCashVoucherIDResponse")]
        System.Threading.Tasks.Task<int> sendCashVoucherIDAsync(int logtakerentid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/SelectUser_LoginPassword", ReplyAction="http://tempuri.org/IServiceRent/SelectUser_LoginPasswordResponse")]
        ClientVehicle.ServerReference.User SelectUser_LoginPassword(string Login, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/SelectUser_LoginPassword", ReplyAction="http://tempuri.org/IServiceRent/SelectUser_LoginPasswordResponse")]
        System.Threading.Tasks.Task<ClientVehicle.ServerReference.User> SelectUser_LoginPasswordAsync(string Login, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/SelectUser", ReplyAction="http://tempuri.org/IServiceRent/SelectUserResponse")]
        ClientVehicle.ServerReference.User SelectUser(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/SelectUser", ReplyAction="http://tempuri.org/IServiceRent/SelectUserResponse")]
        System.Threading.Tasks.Task<ClientVehicle.ServerReference.User> SelectUserAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/SaveUser")]
        void SaveUser(ClientVehicle.ServerReference.User item);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/SaveUser")]
        System.Threading.Tasks.Task SaveUserAsync(ClientVehicle.ServerReference.User item);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/AddUser")]
        void AddUser(ClientVehicle.ServerReference.User item);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/AddUser")]
        System.Threading.Tasks.Task AddUserAsync(ClientVehicle.ServerReference.User item);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/DeleteUser")]
        void DeleteUser(ClientVehicle.ServerReference.User item);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/DeleteUser")]
        System.Threading.Tasks.Task DeleteUserAsync(ClientVehicle.ServerReference.User item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/GetUserVehicle", ReplyAction="http://tempuri.org/IServiceRent/GetUserVehicleResponse")]
        ClientVehicle.ServerReference.Vehicle GetUserVehicle(ClientVehicle.ServerReference.User item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/GetUserVehicle", ReplyAction="http://tempuri.org/IServiceRent/GetUserVehicleResponse")]
        System.Threading.Tasks.Task<ClientVehicle.ServerReference.Vehicle> GetUserVehicleAsync(ClientVehicle.ServerReference.User item);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/SaveBackImage")]
        void SaveBackImage(byte[] Image, string Name, string Extension);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/SaveBackImage")]
        System.Threading.Tasks.Task SaveBackImageAsync(byte[] Image, string Name, string Extension);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/SaveFrontImage")]
        void SaveFrontImage(byte[] Image, string Name, string Extension);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/SaveFrontImage")]
        System.Threading.Tasks.Task SaveFrontImageAsync(byte[] Image, string Name, string Extension);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/BackImageBytes", ReplyAction="http://tempuri.org/IServiceRent/BackImageBytesResponse")]
        byte[] BackImageBytes(ClientVehicle.ServerReference.User item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/BackImageBytes", ReplyAction="http://tempuri.org/IServiceRent/BackImageBytesResponse")]
        System.Threading.Tasks.Task<byte[]> BackImageBytesAsync(ClientVehicle.ServerReference.User item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/FrontImageBytes", ReplyAction="http://tempuri.org/IServiceRent/FrontImageBytesResponse")]
        byte[] FrontImageBytes(ClientVehicle.ServerReference.User item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/FrontImageBytes", ReplyAction="http://tempuri.org/IServiceRent/FrontImageBytesResponse")]
        System.Threading.Tasks.Task<byte[]> FrontImageBytesAsync(ClientVehicle.ServerReference.User item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/IsVehicleValid", ReplyAction="http://tempuri.org/IServiceRent/IsVehicleValidResponse")]
        bool IsVehicleValid(string VIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/IsVehicleValid", ReplyAction="http://tempuri.org/IServiceRent/IsVehicleValidResponse")]
        System.Threading.Tasks.Task<bool> IsVehicleValidAsync(string VIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/SendAllVehicle", ReplyAction="http://tempuri.org/IServiceRent/SendAllVehicleResponse")]
        ClientVehicle.ServerReference.Vehicle[] SendAllVehicle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/SendAllVehicle", ReplyAction="http://tempuri.org/IServiceRent/SendAllVehicleResponse")]
        System.Threading.Tasks.Task<ClientVehicle.ServerReference.Vehicle[]> SendAllVehicleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/SelectAllUser", ReplyAction="http://tempuri.org/IServiceRent/SelectAllUserResponse")]
        ClientVehicle.ServerReference.User[] SelectAllUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/SelectAllUser", ReplyAction="http://tempuri.org/IServiceRent/SelectAllUserResponse")]
        System.Threading.Tasks.Task<ClientVehicle.ServerReference.User[]> SelectAllUserAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceRentCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/onSaveVehicle")]
        void onSaveVehicle(ClientVehicle.ServerReference.Vehicle vehicleObject);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/onDeleteVehicle")]
        void onDeleteVehicle(ClientVehicle.ServerReference.Vehicle vehicleObject);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/sendNotification")]
        void sendNotification(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceRentChannel : ClientVehicle.ServerReference.IServiceRent, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceRentClient : System.ServiceModel.DuplexClientBase<ClientVehicle.ServerReference.IServiceRent>, ClientVehicle.ServerReference.IServiceRent {
        
        public ServiceRentClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServiceRentClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServiceRentClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceRentClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceRentClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public int userConnect() {
            return base.Channel.userConnect();
        }
        
        public System.Threading.Tasks.Task<int> userConnectAsync() {
            return base.Channel.userConnectAsync();
        }
        
        public void userDisconnect(int id) {
            base.Channel.userDisconnect(id);
        }
        
        public System.Threading.Tasks.Task userDisconnectAsync(int id) {
            return base.Channel.userDisconnectAsync(id);
        }
        
        public void selectAllVehicle() {
            base.Channel.selectAllVehicle();
        }
        
        public System.Threading.Tasks.Task selectAllVehicleAsync() {
            return base.Channel.selectAllVehicleAsync();
        }
        
        public void deleteVehicle(ClientVehicle.ServerReference.Vehicle vehicleObject) {
            base.Channel.deleteVehicle(vehicleObject);
        }
        
        public System.Threading.Tasks.Task deleteVehicleAsync(ClientVehicle.ServerReference.Vehicle vehicleObject) {
            return base.Channel.deleteVehicleAsync(vehicleObject);
        }
        
        public void addVehicle(ClientVehicle.ServerReference.Vehicle vehicleObject) {
            base.Channel.addVehicle(vehicleObject);
        }
        
        public System.Threading.Tasks.Task addVehicleAsync(ClientVehicle.ServerReference.Vehicle vehicleObject) {
            return base.Channel.addVehicleAsync(vehicleObject);
        }
        
        public void saveVehicle(ClientVehicle.ServerReference.Vehicle vehicleObject) {
            base.Channel.saveVehicle(vehicleObject);
        }
        
        public System.Threading.Tasks.Task saveVehicleAsync(ClientVehicle.ServerReference.Vehicle vehicleObject) {
            return base.Channel.saveVehicleAsync(vehicleObject);
        }
        
        public int GetAllVehicle() {
            return base.Channel.GetAllVehicle();
        }
        
        public System.Threading.Tasks.Task<int> GetAllVehicleAsync() {
            return base.Channel.GetAllVehicleAsync();
        }
        
        public int GetAllRentVehicle() {
            return base.Channel.GetAllRentVehicle();
        }
        
        public System.Threading.Tasks.Task<int> GetAllRentVehicleAsync() {
            return base.Channel.GetAllRentVehicleAsync();
        }
        
        public int GetAllNoRentVehicle() {
            return base.Channel.GetAllNoRentVehicle();
        }
        
        public System.Threading.Tasks.Task<int> GetAllNoRentVehicleAsync() {
            return base.Channel.GetAllNoRentVehicleAsync();
        }
        
        public ClientVehicle.ServerReference.Vehicle findVehicle(string plate) {
            return base.Channel.findVehicle(plate);
        }
        
        public System.Threading.Tasks.Task<ClientVehicle.ServerReference.Vehicle> findVehicleAsync(string plate) {
            return base.Channel.findVehicleAsync(plate);
        }
        
        public void uploadVehicleImage(byte[] buffer, string name, string extenstion) {
            base.Channel.uploadVehicleImage(buffer, name, extenstion);
        }
        
        public System.Threading.Tasks.Task uploadVehicleImageAsync(byte[] buffer, string name, string extenstion) {
            return base.Channel.uploadVehicleImageAsync(buffer, name, extenstion);
        }
        
        public byte[] vehicleImage(ClientVehicle.ServerReference.Vehicle item) {
            return base.Channel.vehicleImage(item);
        }
        
        public System.Threading.Tasks.Task<byte[]> vehicleImageAsync(ClientVehicle.ServerReference.Vehicle item) {
            return base.Channel.vehicleImageAsync(item);
        }
        
        public void log_AddVehicle(int userid, string VIN) {
            base.Channel.log_AddVehicle(userid, VIN);
        }
        
        public System.Threading.Tasks.Task log_AddVehicleAsync(int userid, string VIN) {
            return base.Channel.log_AddVehicleAsync(userid, VIN);
        }
        
        public void log_Balance(int userid, string card, float value) {
            base.Channel.log_Balance(userid, card, value);
        }
        
        public System.Threading.Tasks.Task log_BalanceAsync(int userid, string card, float value) {
            return base.Channel.log_BalanceAsync(userid, card, value);
        }
        
        public void log_DeleteVehicle(int userid, string VIN, string name) {
            base.Channel.log_DeleteVehicle(userid, VIN, name);
        }
        
        public System.Threading.Tasks.Task log_DeleteVehicleAsync(int userid, string VIN, string name) {
            return base.Channel.log_DeleteVehicleAsync(userid, VIN, name);
        }
        
        public void log_EditVehicle(int userid, string VIN, string str_params) {
            base.Channel.log_EditVehicle(userid, VIN, str_params);
        }
        
        public System.Threading.Tasks.Task log_EditVehicleAsync(int userid, string VIN, string str_params) {
            return base.Channel.log_EditVehicleAsync(userid, VIN, str_params);
        }
        
        public void log_RemoveRent(int userid, int takerentid, System.DateTime date, float balancereturn, float credit) {
            base.Channel.log_RemoveRent(userid, takerentid, date, balancereturn, credit);
        }
        
        public System.Threading.Tasks.Task log_RemoveRentAsync(int userid, int takerentid, System.DateTime date, float balancereturn, float credit) {
            return base.Channel.log_RemoveRentAsync(userid, takerentid, date, balancereturn, credit);
        }
        
        public void log_Request(int admin_userid, int application_userid, int answer) {
            base.Channel.log_Request(admin_userid, application_userid, answer);
        }
        
        public System.Threading.Tasks.Task log_RequestAsync(int admin_userid, int application_userid, int answer) {
            return base.Channel.log_RequestAsync(admin_userid, application_userid, answer);
        }
        
        public int log_TakeRent(int userid, string VIN, float price, int cashVoucherId, System.DateTime startdate, System.DateTime enddate) {
            return base.Channel.log_TakeRent(userid, VIN, price, cashVoucherId, startdate, enddate);
        }
        
        public System.Threading.Tasks.Task<int> log_TakeRentAsync(int userid, string VIN, float price, int cashVoucherId, System.DateTime startdate, System.DateTime enddate) {
            return base.Channel.log_TakeRentAsync(userid, VIN, price, cashVoucherId, startdate, enddate);
        }
        
        public ClientVehicle.ServerReference.StatInfo SendStatInfo(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.SendStatInfo(startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<ClientVehicle.ServerReference.StatInfo> SendStatInfoAsync(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.SendStatInfoAsync(startDate, endDate);
        }
        
        public ClientVehicle.ServerReference.Vehicle selectVehicle(string VIN) {
            return base.Channel.selectVehicle(VIN);
        }
        
        public System.Threading.Tasks.Task<ClientVehicle.ServerReference.Vehicle> selectVehicleAsync(string VIN) {
            return base.Channel.selectVehicleAsync(VIN);
        }
        
        public ClientVehicle.ServerReference.CashVoucherData sendCashVoucherData() {
            return base.Channel.sendCashVoucherData();
        }
        
        public System.Threading.Tasks.Task<ClientVehicle.ServerReference.CashVoucherData> sendCashVoucherDataAsync() {
            return base.Channel.sendCashVoucherDataAsync();
        }
        
        public ClientVehicle.ServerReference.CashVoucher readCashVoucher(int Id) {
            return base.Channel.readCashVoucher(Id);
        }
        
        public System.Threading.Tasks.Task<ClientVehicle.ServerReference.CashVoucher> readCashVoucherAsync(int Id) {
            return base.Channel.readCashVoucherAsync(Id);
        }
        
        public int writeCashVoucher(ClientVehicle.ServerReference.CashVoucher cashVoucher) {
            return base.Channel.writeCashVoucher(cashVoucher);
        }
        
        public System.Threading.Tasks.Task<int> writeCashVoucherAsync(ClientVehicle.ServerReference.CashVoucher cashVoucher) {
            return base.Channel.writeCashVoucherAsync(cashVoucher);
        }
        
        public void setCashVoucherData(string Company, string Street) {
            base.Channel.setCashVoucherData(Company, Street);
        }
        
        public System.Threading.Tasks.Task setCashVoucherDataAsync(string Company, string Street) {
            return base.Channel.setCashVoucherDataAsync(Company, Street);
        }
        
        public int sendCashVoucherID(int logtakerentid) {
            return base.Channel.sendCashVoucherID(logtakerentid);
        }
        
        public System.Threading.Tasks.Task<int> sendCashVoucherIDAsync(int logtakerentid) {
            return base.Channel.sendCashVoucherIDAsync(logtakerentid);
        }
        
        public ClientVehicle.ServerReference.User SelectUser_LoginPassword(string Login, string Password) {
            return base.Channel.SelectUser_LoginPassword(Login, Password);
        }
        
        public System.Threading.Tasks.Task<ClientVehicle.ServerReference.User> SelectUser_LoginPasswordAsync(string Login, string Password) {
            return base.Channel.SelectUser_LoginPasswordAsync(Login, Password);
        }
        
        public ClientVehicle.ServerReference.User SelectUser(int Id) {
            return base.Channel.SelectUser(Id);
        }
        
        public System.Threading.Tasks.Task<ClientVehicle.ServerReference.User> SelectUserAsync(int Id) {
            return base.Channel.SelectUserAsync(Id);
        }
        
        public void SaveUser(ClientVehicle.ServerReference.User item) {
            base.Channel.SaveUser(item);
        }
        
        public System.Threading.Tasks.Task SaveUserAsync(ClientVehicle.ServerReference.User item) {
            return base.Channel.SaveUserAsync(item);
        }
        
        public void AddUser(ClientVehicle.ServerReference.User item) {
            base.Channel.AddUser(item);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(ClientVehicle.ServerReference.User item) {
            return base.Channel.AddUserAsync(item);
        }
        
        public void DeleteUser(ClientVehicle.ServerReference.User item) {
            base.Channel.DeleteUser(item);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(ClientVehicle.ServerReference.User item) {
            return base.Channel.DeleteUserAsync(item);
        }
        
        public ClientVehicle.ServerReference.Vehicle GetUserVehicle(ClientVehicle.ServerReference.User item) {
            return base.Channel.GetUserVehicle(item);
        }
        
        public System.Threading.Tasks.Task<ClientVehicle.ServerReference.Vehicle> GetUserVehicleAsync(ClientVehicle.ServerReference.User item) {
            return base.Channel.GetUserVehicleAsync(item);
        }
        
        public void SaveBackImage(byte[] Image, string Name, string Extension) {
            base.Channel.SaveBackImage(Image, Name, Extension);
        }
        
        public System.Threading.Tasks.Task SaveBackImageAsync(byte[] Image, string Name, string Extension) {
            return base.Channel.SaveBackImageAsync(Image, Name, Extension);
        }
        
        public void SaveFrontImage(byte[] Image, string Name, string Extension) {
            base.Channel.SaveFrontImage(Image, Name, Extension);
        }
        
        public System.Threading.Tasks.Task SaveFrontImageAsync(byte[] Image, string Name, string Extension) {
            return base.Channel.SaveFrontImageAsync(Image, Name, Extension);
        }
        
        public byte[] BackImageBytes(ClientVehicle.ServerReference.User item) {
            return base.Channel.BackImageBytes(item);
        }
        
        public System.Threading.Tasks.Task<byte[]> BackImageBytesAsync(ClientVehicle.ServerReference.User item) {
            return base.Channel.BackImageBytesAsync(item);
        }
        
        public byte[] FrontImageBytes(ClientVehicle.ServerReference.User item) {
            return base.Channel.FrontImageBytes(item);
        }
        
        public System.Threading.Tasks.Task<byte[]> FrontImageBytesAsync(ClientVehicle.ServerReference.User item) {
            return base.Channel.FrontImageBytesAsync(item);
        }
        
        public bool IsVehicleValid(string VIN) {
            return base.Channel.IsVehicleValid(VIN);
        }
        
        public System.Threading.Tasks.Task<bool> IsVehicleValidAsync(string VIN) {
            return base.Channel.IsVehicleValidAsync(VIN);
        }
        
        public ClientVehicle.ServerReference.Vehicle[] SendAllVehicle() {
            return base.Channel.SendAllVehicle();
        }
        
        public System.Threading.Tasks.Task<ClientVehicle.ServerReference.Vehicle[]> SendAllVehicleAsync() {
            return base.Channel.SendAllVehicleAsync();
        }
        
        public ClientVehicle.ServerReference.User[] SelectAllUser() {
            return base.Channel.SelectAllUser();
        }
        
        public System.Threading.Tasks.Task<ClientVehicle.ServerReference.User[]> SelectAllUserAsync() {
            return base.Channel.SelectAllUserAsync();
        }
    }
}
