//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRC_Redesign.ServiceRent {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Admin", Namespace="http://schemas.datacontract.org/2004/07/WCF_Rent.HeaderFile")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TRC_Redesign.ServiceRent.Account))]
    public partial class Admin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int levelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int level {
            get {
                return this.levelField;
            }
            set {
                if ((this.levelField.Equals(value) != true)) {
                    this.levelField = value;
                    this.RaisePropertyChanged("level");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/WCF_Rent.HeaderFile")]
    [System.SerializableAttribute()]
    public partial class Account : TRC_Redesign.ServiceRent.Admin {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int acceptedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float balanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateCreateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int documentidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fathernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string secondnameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int accepted {
            get {
                return this.acceptedField;
            }
            set {
                if ((this.acceptedField.Equals(value) != true)) {
                    this.acceptedField = value;
                    this.RaisePropertyChanged("accepted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float balance {
            get {
                return this.balanceField;
            }
            set {
                if ((this.balanceField.Equals(value) != true)) {
                    this.balanceField = value;
                    this.RaisePropertyChanged("balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateCreate {
            get {
                return this.dateCreateField;
            }
            set {
                if ((this.dateCreateField.Equals(value) != true)) {
                    this.dateCreateField = value;
                    this.RaisePropertyChanged("dateCreate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int documentid {
            get {
                return this.documentidField;
            }
            set {
                if ((this.documentidField.Equals(value) != true)) {
                    this.documentidField = value;
                    this.RaisePropertyChanged("documentid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fathername {
            get {
                return this.fathernameField;
            }
            set {
                if ((object.ReferenceEquals(this.fathernameField, value) != true)) {
                    this.fathernameField = value;
                    this.RaisePropertyChanged("fathername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string secondname {
            get {
                return this.secondnameField;
            }
            set {
                if ((object.ReferenceEquals(this.secondnameField, value) != true)) {
                    this.secondnameField = value;
                    this.RaisePropertyChanged("secondname");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rent", Namespace="http://schemas.datacontract.org/2004/07/WCF_Rent.HeaderFile")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TRC_Redesign.ServiceRent.Vehicle))]
    public partial class Rent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int client_documentidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime end_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int isrentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime start_dateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int client_documentid {
            get {
                return this.client_documentidField;
            }
            set {
                if ((this.client_documentidField.Equals(value) != true)) {
                    this.client_documentidField = value;
                    this.RaisePropertyChanged("client_documentid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime end_date {
            get {
                return this.end_dateField;
            }
            set {
                if ((this.end_dateField.Equals(value) != true)) {
                    this.end_dateField = value;
                    this.RaisePropertyChanged("end_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int isrent {
            get {
                return this.isrentField;
            }
            set {
                if ((this.isrentField.Equals(value) != true)) {
                    this.isrentField = value;
                    this.RaisePropertyChanged("isrent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime start_date {
            get {
                return this.start_dateField;
            }
            set {
                if ((this.start_dateField.Equals(value) != true)) {
                    this.start_dateField = value;
                    this.RaisePropertyChanged("start_date");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vehicle", Namespace="http://schemas.datacontract.org/2004/07/WCF_Rent.HeaderFile")]
    [System.SerializableAttribute()]
    public partial class Vehicle : TRC_Redesign.ServiceRent.Rent {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float fuelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string image_linkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float maxfuelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int maxspeedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float mileageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string plateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transmissionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                if ((object.ReferenceEquals(this.categoryField, value) != true)) {
                    this.categoryField = value;
                    this.RaisePropertyChanged("category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float fuel {
            get {
                return this.fuelField;
            }
            set {
                if ((this.fuelField.Equals(value) != true)) {
                    this.fuelField = value;
                    this.RaisePropertyChanged("fuel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image_link {
            get {
                return this.image_linkField;
            }
            set {
                if ((object.ReferenceEquals(this.image_linkField, value) != true)) {
                    this.image_linkField = value;
                    this.RaisePropertyChanged("image_link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float maxfuel {
            get {
                return this.maxfuelField;
            }
            set {
                if ((this.maxfuelField.Equals(value) != true)) {
                    this.maxfuelField = value;
                    this.RaisePropertyChanged("maxfuel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int maxspeed {
            get {
                return this.maxspeedField;
            }
            set {
                if ((this.maxspeedField.Equals(value) != true)) {
                    this.maxspeedField = value;
                    this.RaisePropertyChanged("maxspeed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float mileage {
            get {
                return this.mileageField;
            }
            set {
                if ((this.mileageField.Equals(value) != true)) {
                    this.mileageField = value;
                    this.RaisePropertyChanged("mileage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string model {
            get {
                return this.modelField;
            }
            set {
                if ((object.ReferenceEquals(this.modelField, value) != true)) {
                    this.modelField = value;
                    this.RaisePropertyChanged("model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string plate {
            get {
                return this.plateField;
            }
            set {
                if ((object.ReferenceEquals(this.plateField, value) != true)) {
                    this.plateField = value;
                    this.RaisePropertyChanged("plate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string transmission {
            get {
                return this.transmissionField;
            }
            set {
                if ((object.ReferenceEquals(this.transmissionField, value) != true)) {
                    this.transmissionField = value;
                    this.RaisePropertyChanged("transmission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRent.IServiceRent")]
    public interface IServiceRent {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/userConnect", ReplyAction="http://tempuri.org/IServiceRent/userConnectResponse")]
        int userConnect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/userConnect", ReplyAction="http://tempuri.org/IServiceRent/userConnectResponse")]
        System.Threading.Tasks.Task<int> userConnectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/userDisconnect", ReplyAction="http://tempuri.org/IServiceRent/userDisconnectResponse")]
        void userDisconnect(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/userDisconnect", ReplyAction="http://tempuri.org/IServiceRent/userDisconnectResponse")]
        System.Threading.Tasks.Task userDisconnectAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/selectAccount", ReplyAction="http://tempuri.org/IServiceRent/selectAccountResponse")]
        TRC_Redesign.ServiceRent.Account selectAccount(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/selectAccount", ReplyAction="http://tempuri.org/IServiceRent/selectAccountResponse")]
        System.Threading.Tasks.Task<TRC_Redesign.ServiceRent.Account> selectAccountAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/createSqlConnection")]
        void createSqlConnection(string path);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/createSqlConnection")]
        System.Threading.Tasks.Task createSqlConnectionAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/selectAllVehicle")]
        void selectAllVehicle();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/selectAllVehicle")]
        System.Threading.Tasks.Task selectAllVehicleAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/deleteVehicle")]
        void deleteVehicle(TRC_Redesign.ServiceRent.Vehicle vehicleObject);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/deleteVehicle")]
        System.Threading.Tasks.Task deleteVehicleAsync(TRC_Redesign.ServiceRent.Vehicle vehicleObject);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/addVehicle")]
        void addVehicle(TRC_Redesign.ServiceRent.Vehicle vehicleObject);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/addVehicle")]
        System.Threading.Tasks.Task addVehicleAsync(TRC_Redesign.ServiceRent.Vehicle vehicleObject);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/saveVehicle")]
        void saveVehicle(TRC_Redesign.ServiceRent.Vehicle vehicleObject);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/saveVehicle")]
        System.Threading.Tasks.Task saveVehicleAsync(TRC_Redesign.ServiceRent.Vehicle vehicleObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/isAccountValid", ReplyAction="http://tempuri.org/IServiceRent/isAccountValidResponse")]
        bool isAccountValid(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/isAccountValid", ReplyAction="http://tempuri.org/IServiceRent/isAccountValidResponse")]
        System.Threading.Tasks.Task<bool> isAccountValidAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/isSqlConnection", ReplyAction="http://tempuri.org/IServiceRent/isSqlConnectionResponse")]
        bool isSqlConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/isSqlConnection", ReplyAction="http://tempuri.org/IServiceRent/isSqlConnectionResponse")]
        System.Threading.Tasks.Task<bool> isSqlConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/getUserVehicle", ReplyAction="http://tempuri.org/IServiceRent/getUserVehicleResponse")]
        TRC_Redesign.ServiceRent.Vehicle getUserVehicle(TRC_Redesign.ServiceRent.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/getUserVehicle", ReplyAction="http://tempuri.org/IServiceRent/getUserVehicleResponse")]
        System.Threading.Tasks.Task<TRC_Redesign.ServiceRent.Vehicle> getUserVehicleAsync(TRC_Redesign.ServiceRent.Account account);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/saveAccount")]
        void saveAccount(TRC_Redesign.ServiceRent.Account accountObject);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/saveAccount")]
        System.Threading.Tasks.Task saveAccountAsync(TRC_Redesign.ServiceRent.Account accountObject);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/addAccount")]
        void addAccount(TRC_Redesign.ServiceRent.Account accountObject);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/addAccount")]
        System.Threading.Tasks.Task addAccountAsync(TRC_Redesign.ServiceRent.Account accountObject);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/deleteAccount")]
        void deleteAccount(TRC_Redesign.ServiceRent.Account accountObject);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServiceRent/deleteAccount")]
        System.Threading.Tasks.Task deleteAccountAsync(TRC_Redesign.ServiceRent.Account accountObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/createVehicleObjectParams", ReplyAction="http://tempuri.org/IServiceRent/createVehicleObjectParamsResponse")]
        TRC_Redesign.ServiceRent.Vehicle[] createVehicleObjectParams(int min, int max, int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/createVehicleObjectParams", ReplyAction="http://tempuri.org/IServiceRent/createVehicleObjectParamsResponse")]
        System.Threading.Tasks.Task<TRC_Redesign.ServiceRent.Vehicle[]> createVehicleObjectParamsAsync(int min, int max, int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/GetAllVehicle", ReplyAction="http://tempuri.org/IServiceRent/GetAllVehicleResponse")]
        int GetAllVehicle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/GetAllVehicle", ReplyAction="http://tempuri.org/IServiceRent/GetAllVehicleResponse")]
        System.Threading.Tasks.Task<int> GetAllVehicleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/GetAllRentVehicle", ReplyAction="http://tempuri.org/IServiceRent/GetAllRentVehicleResponse")]
        int GetAllRentVehicle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/GetAllRentVehicle", ReplyAction="http://tempuri.org/IServiceRent/GetAllRentVehicleResponse")]
        System.Threading.Tasks.Task<int> GetAllRentVehicleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/GetAllNoRentVehicle", ReplyAction="http://tempuri.org/IServiceRent/GetAllNoRentVehicleResponse")]
        int GetAllNoRentVehicle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/GetAllNoRentVehicle", ReplyAction="http://tempuri.org/IServiceRent/GetAllNoRentVehicleResponse")]
        System.Threading.Tasks.Task<int> GetAllNoRentVehicleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/noAcceptedAccount", ReplyAction="http://tempuri.org/IServiceRent/noAcceptedAccountResponse")]
        TRC_Redesign.ServiceRent.Account noAcceptedAccount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/noAcceptedAccount", ReplyAction="http://tempuri.org/IServiceRent/noAcceptedAccountResponse")]
        System.Threading.Tasks.Task<TRC_Redesign.ServiceRent.Account> noAcceptedAccountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/findVehicle", ReplyAction="http://tempuri.org/IServiceRent/findVehicleResponse")]
        TRC_Redesign.ServiceRent.Vehicle findVehicle(string plate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/findVehicle", ReplyAction="http://tempuri.org/IServiceRent/findVehicleResponse")]
        System.Threading.Tasks.Task<TRC_Redesign.ServiceRent.Vehicle> findVehicleAsync(string plate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceRentChannel : TRC_Redesign.ServiceRent.IServiceRent, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceRentClient : System.ServiceModel.ClientBase<TRC_Redesign.ServiceRent.IServiceRent>, TRC_Redesign.ServiceRent.IServiceRent {
        
        public ServiceRentClient(System.ServiceModel.InstanceContext instanceContext) {
        }
        
        public ServiceRentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceRentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceRentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceRentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int userConnect() {
            return base.Channel.userConnect();
        }
        
        public System.Threading.Tasks.Task<int> userConnectAsync() {
            return base.Channel.userConnectAsync();
        }
        
        public void userDisconnect(int id) {
            base.Channel.userDisconnect(id);
        }
        
        public System.Threading.Tasks.Task userDisconnectAsync(int id) {
            return base.Channel.userDisconnectAsync(id);
        }
        
        public TRC_Redesign.ServiceRent.Account selectAccount(string login, string password) {
            return base.Channel.selectAccount(login, password);
        }
        
        public System.Threading.Tasks.Task<TRC_Redesign.ServiceRent.Account> selectAccountAsync(string login, string password) {
            return base.Channel.selectAccountAsync(login, password);
        }
        
        public void createSqlConnection(string path) {
            base.Channel.createSqlConnection(path);
        }
        
        public System.Threading.Tasks.Task createSqlConnectionAsync(string path) {
            return base.Channel.createSqlConnectionAsync(path);
        }
        
        public void selectAllVehicle() {
            base.Channel.selectAllVehicle();
        }
        
        public System.Threading.Tasks.Task selectAllVehicleAsync() {
            return base.Channel.selectAllVehicleAsync();
        }
        
        public void deleteVehicle(TRC_Redesign.ServiceRent.Vehicle vehicleObject) {
            base.Channel.deleteVehicle(vehicleObject);
        }
        
        public System.Threading.Tasks.Task deleteVehicleAsync(TRC_Redesign.ServiceRent.Vehicle vehicleObject) {
            return base.Channel.deleteVehicleAsync(vehicleObject);
        }
        
        public void addVehicle(TRC_Redesign.ServiceRent.Vehicle vehicleObject) {
            base.Channel.addVehicle(vehicleObject);
        }
        
        public System.Threading.Tasks.Task addVehicleAsync(TRC_Redesign.ServiceRent.Vehicle vehicleObject) {
            return base.Channel.addVehicleAsync(vehicleObject);
        }
        
        public void saveVehicle(TRC_Redesign.ServiceRent.Vehicle vehicleObject) {
            base.Channel.saveVehicle(vehicleObject);
        }
        
        public System.Threading.Tasks.Task saveVehicleAsync(TRC_Redesign.ServiceRent.Vehicle vehicleObject) {
            return base.Channel.saveVehicleAsync(vehicleObject);
        }
        
        public bool isAccountValid(string login) {
            return base.Channel.isAccountValid(login);
        }
        
        public System.Threading.Tasks.Task<bool> isAccountValidAsync(string login) {
            return base.Channel.isAccountValidAsync(login);
        }
        
        public bool isSqlConnection() {
            return base.Channel.isSqlConnection();
        }
        
        public System.Threading.Tasks.Task<bool> isSqlConnectionAsync() {
            return base.Channel.isSqlConnectionAsync();
        }
        
        public TRC_Redesign.ServiceRent.Vehicle getUserVehicle(TRC_Redesign.ServiceRent.Account account) {
            return base.Channel.getUserVehicle(account);
        }
        
        public System.Threading.Tasks.Task<TRC_Redesign.ServiceRent.Vehicle> getUserVehicleAsync(TRC_Redesign.ServiceRent.Account account) {
            return base.Channel.getUserVehicleAsync(account);
        }
        
        public void saveAccount(TRC_Redesign.ServiceRent.Account accountObject) {
            base.Channel.saveAccount(accountObject);
        }
        
        public System.Threading.Tasks.Task saveAccountAsync(TRC_Redesign.ServiceRent.Account accountObject) {
            return base.Channel.saveAccountAsync(accountObject);
        }
        
        public void addAccount(TRC_Redesign.ServiceRent.Account accountObject) {
            base.Channel.addAccount(accountObject);
        }
        
        public System.Threading.Tasks.Task addAccountAsync(TRC_Redesign.ServiceRent.Account accountObject) {
            return base.Channel.addAccountAsync(accountObject);
        }
        
        public void deleteAccount(TRC_Redesign.ServiceRent.Account accountObject) {
            base.Channel.deleteAccount(accountObject);
        }
        
        public System.Threading.Tasks.Task deleteAccountAsync(TRC_Redesign.ServiceRent.Account accountObject) {
            return base.Channel.deleteAccountAsync(accountObject);
        }
        
        public TRC_Redesign.ServiceRent.Vehicle[] createVehicleObjectParams(int min, int max, int type) {
            return base.Channel.createVehicleObjectParams(min, max, type);
        }
        
        public System.Threading.Tasks.Task<TRC_Redesign.ServiceRent.Vehicle[]> createVehicleObjectParamsAsync(int min, int max, int type) {
            return base.Channel.createVehicleObjectParamsAsync(min, max, type);
        }
        
        public int GetAllVehicle() {
            return base.Channel.GetAllVehicle();
        }
        
        public System.Threading.Tasks.Task<int> GetAllVehicleAsync() {
            return base.Channel.GetAllVehicleAsync();
        }
        
        public int GetAllRentVehicle() {
            return base.Channel.GetAllRentVehicle();
        }
        
        public System.Threading.Tasks.Task<int> GetAllRentVehicleAsync() {
            return base.Channel.GetAllRentVehicleAsync();
        }
        
        public int GetAllNoRentVehicle() {
            return base.Channel.GetAllNoRentVehicle();
        }
        
        public System.Threading.Tasks.Task<int> GetAllNoRentVehicleAsync() {
            return base.Channel.GetAllNoRentVehicleAsync();
        }
        
        public TRC_Redesign.ServiceRent.Account noAcceptedAccount() {
            return base.Channel.noAcceptedAccount();
        }
        
        public System.Threading.Tasks.Task<TRC_Redesign.ServiceRent.Account> noAcceptedAccountAsync() {
            return base.Channel.noAcceptedAccountAsync();
        }
        
        public TRC_Redesign.ServiceRent.Vehicle findVehicle(string plate) {
            return base.Channel.findVehicle(plate);
        }
        
        public System.Threading.Tasks.Task<TRC_Redesign.ServiceRent.Vehicle> findVehicleAsync(string plate) {
            return base.Channel.findVehicleAsync(plate);
        }
    }
}
