//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRC_Redesign.ServiceRent {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRent.IServiceRent")]
    public interface IServiceRent {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/userConnect", ReplyAction="http://tempuri.org/IServiceRent/userConnectResponse")]
        int userConnect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/userConnect", ReplyAction="http://tempuri.org/IServiceRent/userConnectResponse")]
        System.Threading.Tasks.Task<int> userConnectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/userDisconnect", ReplyAction="http://tempuri.org/IServiceRent/userDisconnectResponse")]
        void userDisconnect(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRent/userDisconnect", ReplyAction="http://tempuri.org/IServiceRent/userDisconnectResponse")]
        System.Threading.Tasks.Task userDisconnectAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceRentChannel : TRC_Redesign.ServiceRent.IServiceRent, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceRentClient : System.ServiceModel.ClientBase<TRC_Redesign.ServiceRent.IServiceRent>, TRC_Redesign.ServiceRent.IServiceRent {
        
        public ServiceRentClient() {
        }
        
        public ServiceRentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceRentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceRentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceRentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int userConnect() {
            return base.Channel.userConnect();
        }
        
        public System.Threading.Tasks.Task<int> userConnectAsync() {
            return base.Channel.userConnectAsync();
        }
        
        public void userDisconnect(int id) {
            base.Channel.userDisconnect(id);
        }
        
        public System.Threading.Tasks.Task userDisconnectAsync(int id) {
            return base.Channel.userDisconnectAsync(id);
        }
    }
}
